-- Re-issues migrations/0021_plain_harpoon.sql at the correct sequence number.
-- That file was generated by drizzle-kit and landed numbered 0021, behind the
-- hand-written chain which had already reached 0070, so a deployment applying
-- migrations in order walks straight past it. Guarded with IF NOT EXISTS so it
-- is a no-op on any database where 0021_plain_harpoon.sql was already applied.
ALTER TABLE "sales_quotations" ADD COLUMN IF NOT EXISTS "subject" text;
ALTER TABLE "sales_invoices" ADD COLUMN IF NOT EXISTS "subject" text;
ALTER TABLE "proforma_invoices" ADD COLUMN IF NOT EXISTS "subject" text;
ALTER TABLE "credit_notes" ADD COLUMN IF NOT EXISTS "subject" text;
ALTER TABLE "purchase_orders" ADD COLUMN IF NOT EXISTS "subject" text;
ALTER TABLE "purchase_invoices" ADD COLUMN IF NOT EXISTS "subject" text;
